theme: jekyll-theme-midnight
title: The Mirin Template
kramdown:
    coderay_tab_width: 4
plugins:
  - jekyll-redirect-from
github:
  repository_url: https://github.com/XeroOl/notitg-mirin/tree/gh-pages
